### ISSUE TITLE
Error when preparing COCO annotation file from a single YOLO annotation file

### ISSUE THREAD

**Issue by talasalim** [Taeyoung96/Yolo-to-COCO-format-converter#17]
I have a dataset with both labeled and unlabeled images(hence some empty txt files). When I run the validation txt file using main.py it works perfectly but when I run main.py on the train txt file it shows me this error: 

`Start!
Processing 2588 ...Traceback (most recent call last):
  File "C:\Users\Tala\Desktop\Yolo-to-COCO-format-converter\main.py", line 233, in <module>
    main(options)
  File "C:\Users\Tala\Desktop\Yolo-to-COCO-format-converter\main.py", line 215, in main
    ) = get_images_info_and_annotations(opt)
  File "C:\Users\Tala\Desktop\Yolo-to-COCO-format-converter\main.py", line 47, in get_images_info_and_annotations
    w, h = imagesize.get(str(file_path))
  File "C:\Users\Tala\anaconda3\lib\site-packages\imagesize.py", line 96, in get
    fhandle = open(filepath, 'rb')
PermissionError: [Errno 13] Permission denied: '.'`

I'm not sure why it stops processing at 2588

**Comment by Taeyoung96** [comment]
@talasalim   
Based on the error you sent me, I think it's because there's a problem with the file path or there's no authorization.

**Comment by Taeyoung96** [comment]
I'm closing this issue because it hasn't been updated in a long time, please reopen it if you have any problems.
